import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { LeftNav } from "@/components/layout/LeftNav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* これがページの1層目になる */}
        <LeftNav />
        <div style={styles.contentContainer}>{children}</div>
      </body>
    </html>
  );
}

const styles: { [key: string]: React.CSSProperties } = {
  contentContainer: {
    marginLeft: "10%", // ナビゲーションバーの右側に表示
    width: "90%",
    display: "flex",
  },
};
